import { Provider, Patient, MedicalRequest } from './types';

export const mockProviders: Provider[] = [
  {
    id: '1',
    email: 'dr.smith@email.com',
    name: 'Dr. Sarah Smith',
    role: 'provider',
    licenseNumber: 'MD12345',
    specialties: ['Family Medicine', 'Internal Medicine'],
    zipCode: '10001',
    licenseStates: ['NY', 'NJ', 'CT'],
    yearsExperience: 12,
    rating: 4.8,
    profileImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face',
    isAvailable: true,
    acceptedInsurance: ['Blue Cross', 'Aetna', 'Cigna', 'United Healthcare'],
    createdAt: new Date('2022-01-15'),
  },
  {
    id: '2',
    email: 'dr.johnson@email.com',
    name: 'Dr. Michael Johnson',
    role: 'provider',
    licenseNumber: 'MD23456',
    specialties: ['Cardiology', 'Internal Medicine'],
    zipCode: '10002',
    licenseStates: ['NY', 'PA'],
    yearsExperience: 18,
    rating: 4.9,
    profileImage: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face',
    isAvailable: true,
    acceptedInsurance: ['Blue Cross', 'Aetna', 'Medicare'],
    createdAt: new Date('2021-03-20'),
  },
  {
    id: '3',
    email: 'dr.williams@email.com',
    name: 'Dr. Emily Williams',
    role: 'provider',
    licenseNumber: 'MD34567',
    specialties: ['Dermatology', 'Cosmetic Dermatology'],
    zipCode: '10003',
    licenseStates: ['NY', 'CA', 'FL'],
    yearsExperience: 8,
    rating: 4.7,
    profileImage: 'https://images.unsplash.com/photo-1594824204989-5c12b0f8896c?w=400&h=400&fit=crop&crop=face',
    isAvailable: false,
    acceptedInsurance: ['Cigna', 'United Healthcare', 'Blue Shield'],
    createdAt: new Date('2020-07-10'),
  },
  {
    id: '4',
    email: 'dr.brown@email.com',
    name: 'Dr. David Brown',
    role: 'provider',
    licenseNumber: 'MD45678',
    specialties: ['Psychiatry', 'Psychology'],
    zipCode: '10004',
    licenseStates: ['NY', 'NJ'],
    yearsExperience: 15,
    rating: 4.9,
    profileImage: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&crop=face',
    isAvailable: true,
    acceptedInsurance: ['Blue Cross', 'Aetna', 'Cigna', 'United Healthcare', 'Medicare'],
    createdAt: new Date('2019-11-05'),
  },
  {
    id: '5',
    email: 'dr.davis@email.com',
    name: 'Dr. Lisa Davis',
    role: 'provider',
    licenseNumber: 'MD56789',
    specialties: ['Pediatrics', 'Family Medicine'],
    zipCode: '10005',
    licenseStates: ['NY', 'CT'],
    yearsExperience: 10,
    rating: 4.8,
    profileImage: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&h=400&fit=crop&crop=face',
    isAvailable: true,
    acceptedInsurance: ['Blue Cross', 'United Healthcare', 'Medicaid'],
    createdAt: new Date('2021-09-12'),
  },
  {
    id: '6',
    email: 'dr.rodriguez@email.com',
    name: 'Dr. Maria Rodriguez',
    role: 'provider',
    licenseNumber: 'MD67890',
    specialties: ['Emergency Medicine', 'Critical Care'],
    zipCode: '10006',
    licenseStates: ['NY', 'NJ', 'FL'],
    yearsExperience: 14,
    rating: 4.9,
    profileImage: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&crop=face',
    isAvailable: true,
    acceptedInsurance: ['Blue Cross', 'Aetna', 'Cigna', 'United Healthcare'],
    createdAt: new Date('2020-05-18'),
  },
  {
    id: '7',
    email: 'dr.chen@email.com',
    name: 'Dr. James Chen',
    role: 'provider',
    licenseNumber: 'MD78901',
    specialties: ['Orthopedics', 'Sports Medicine'],
    zipCode: '10007',
    licenseStates: ['NY', 'CA', 'TX'],
    yearsExperience: 16,
    rating: 4.8,
    profileImage: 'https://images.unsplash.com/photo-1632910121591-29e2484c0259?w=400&h=400&fit=crop&crop=face',
    isAvailable: true,
    acceptedInsurance: ['Blue Cross', 'United Healthcare', 'Medicare'],
    createdAt: new Date('2019-08-22'),
  },
  {
    id: '8',
    email: 'dr.patel@email.com',
    name: 'Dr. Priya Patel',
    role: 'provider',
    licenseNumber: 'MD89012',
    specialties: ['Endocrinology', 'Diabetes Care'],
    zipCode: '10008',
    licenseStates: ['NY', 'NJ', 'PA'],
    yearsExperience: 11,
    rating: 4.9,
    profileImage: 'https://images.unsplash.com/photo-1609902726285-00668009f004?w=400&h=400&fit=crop&crop=face',
    isAvailable: true,
    acceptedInsurance: ['Aetna', 'Cigna', 'Blue Shield'],
    createdAt: new Date('2021-12-10'),
  },
  {
    id: '9',
    email: 'dr.taylor@email.com',
    name: 'Dr. Robert Taylor',
    role: 'provider',
    licenseNumber: 'MD90123',
    specialties: ['Gastroenterology', 'Hepatology'],
    zipCode: '10009',
    licenseStates: ['NY', 'CT'],
    yearsExperience: 20,
    rating: 4.7,
    profileImage: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&crop=face',
    isAvailable: false,
    acceptedInsurance: ['Blue Cross', 'Medicare', 'Medicaid'],
    createdAt: new Date('2018-02-14'),
  },
  {
    id: '10',
    email: 'dr.martinez@email.com',
    name: 'Dr. Ana Martinez',
    role: 'provider',
    licenseNumber: 'MD01234',
    specialties: ['Neurology', 'Sleep Medicine'],
    zipCode: '10010',
    licenseStates: ['NY', 'FL', 'TX'],
    yearsExperience: 13,
    rating: 4.8,
    profileImage: 'https://images.unsplash.com/photo-1594824204989-5c12b0f8896c?w=400&h=400&fit=crop&crop=face',
    isAvailable: true,
    acceptedInsurance: ['Blue Cross', 'Aetna', 'United Healthcare'],
    createdAt: new Date('2020-11-03'),
  },
];

export const mockPatients: Patient[] = [
  {
    id: '1',
    email: 'john.doe@email.com',
    name: 'John Doe',
    role: 'patient',
    dateOfBirth: new Date('1985-06-15'),
    zipCode: '10001',
    phone: '(555) 123-4567',
    emergencyContact: {
      name: 'Jane Doe',
      phone: '(555) 987-6543',
      relationship: 'Spouse',
    },
    createdAt: new Date('2023-01-10'),
  },
  {
    id: '2',
    email: 'mary.smith@email.com',
    name: 'Mary Smith',
    role: 'patient',
    dateOfBirth: new Date('1990-03-22'),
    zipCode: '10002',
    phone: '(555) 234-5678',
    emergencyContact: {
      name: 'Robert Smith',
      phone: '(555) 876-5432',
      relationship: 'Father',
    },
    createdAt: new Date('2023-02-05'),
  },
  {
    id: '3',
    email: 'alex.jones@email.com',
    name: 'Alex Jones',
    role: 'patient',
    dateOfBirth: new Date('1978-11-08'),
    zipCode: '10003',
    phone: '(555) 345-6789',
    emergencyContact: {
      name: 'Sarah Jones',
      phone: '(555) 765-4321',
      relationship: 'Spouse',
    },
    createdAt: new Date('2023-03-15'),
  },
  {
    id: '4',
    email: 'linda.wilson@email.com',
    name: 'Linda Wilson',
    role: 'patient',
    dateOfBirth: new Date('1965-09-12'),
    zipCode: '10004',
    phone: '(555) 456-7890',
    emergencyContact: {
      name: 'Mark Wilson',
      phone: '(555) 654-3210',
      relationship: 'Spouse',
    },
    createdAt: new Date('2023-01-20'),
  },
  {
    id: '5',
    email: 'david.garcia@email.com',
    name: 'David Garcia',
    role: 'patient',
    dateOfBirth: new Date('1992-12-03'),
    zipCode: '10005',
    phone: '(555) 567-8901',
    emergencyContact: {
      name: 'Maria Garcia',
      phone: '(555) 543-2109',
      relationship: 'Mother',
    },
    createdAt: new Date('2023-02-18'),
  },
  {
    id: '6',
    email: 'jennifer.brown@email.com',
    name: 'Jennifer Brown',
    role: 'patient',
    dateOfBirth: new Date('1988-04-25'),
    zipCode: '10006',
    phone: '(555) 678-9012',
    emergencyContact: {
      name: 'Michael Brown',
      phone: '(555) 432-1098',
      relationship: 'Brother',
    },
    createdAt: new Date('2023-03-10'),
  },
  {
    id: '7',
    email: 'kevin.lee@email.com',
    name: 'Kevin Lee',
    role: 'patient',
    dateOfBirth: new Date('1975-07-18'),
    zipCode: '10007',
    phone: '(555) 789-0123',
    emergencyContact: {
      name: 'Anna Lee',
      phone: '(555) 321-0987',
      relationship: 'Spouse',
    },
    createdAt: new Date('2023-02-25'),
  },
  {
    id: '8',
    email: 'sophie.martin@email.com',
    name: 'Sophie Martin',
    role: 'patient',
    dateOfBirth: new Date('1995-11-30'),
    zipCode: '10008',
    phone: '(555) 890-1234',
    emergencyContact: {
      name: 'Paul Martin',
      phone: '(555) 210-9876',
      relationship: 'Father',
    },
    createdAt: new Date('2023-04-05'),
  },
  {
    id: '9',
    email: 'robert.taylor@email.com',
    name: 'Robert Taylor',
    role: 'patient',
    dateOfBirth: new Date('1982-08-14'),
    zipCode: '10009',
    phone: '(555) 901-2345',
    emergencyContact: {
      name: 'Emma Taylor',
      phone: '(555) 109-8765',
      relationship: 'Spouse',
    },
    createdAt: new Date('2023-03-28'),
  },
  {
    id: '10',
    email: 'amanda.davis@email.com',
    name: 'Amanda Davis',
    role: 'patient',
    dateOfBirth: new Date('1987-01-09'),
    zipCode: '10010',
    phone: '(555) 012-3456',
    emergencyContact: {
      name: 'James Davis',
      phone: '(555) 098-7654',
      relationship: 'Husband',
    },
    createdAt: new Date('2023-04-12'),
  },
  {
    id: '11',
    email: 'carlos.rodriguez@email.com',
    name: 'Carlos Rodriguez',
    role: 'patient',
    dateOfBirth: new Date('1979-05-21'),
    zipCode: '10001',
    phone: '(555) 321-6547',
    emergencyContact: {
      name: 'Isabella Rodriguez',
      phone: '(555) 789-4561',
      relationship: 'Wife',
    },
    createdAt: new Date('2023-01-30'),
  },
  {
    id: '12',
    email: 'rachel.chen@email.com',
    name: 'Rachel Chen',
    role: 'patient',
    dateOfBirth: new Date('1993-10-16'),
    zipCode: '10002',
    phone: '(555) 654-9873',
    emergencyContact: {
      name: 'Lisa Chen',
      phone: '(555) 147-2580',
      relationship: 'Sister',
    },
    createdAt: new Date('2023-02-14'),
  },
];

export const mockRequests: MedicalRequest[] = [
  // Completed/Ongoing Cases
  {
    id: '1',
    patientId: '1',
    patient: mockPatients[0],
    providerId: '1',
    provider: mockProviders[0],
    type: 'general-consultation',
    symptoms: 'Persistent headache, fatigue',
    description: 'I have been experiencing severe headaches for the past week, along with unusual fatigue. The headaches are worse in the morning and seem to be getting more frequent.',
    status: 'completed',
    createdAt: new Date('2024-01-20T09:00:00'),
    updatedAt: new Date('2024-01-20T14:30:00'),
    zipCode: '10001',
  },
  {
    id: '2',
    patientId: '4',
    patient: mockPatients[3],
    providerId: '8',
    provider: mockProviders[7],
    type: 'prescription-request',
    symptoms: 'Diabetes management',
    description: 'Need to refill my metformin prescription. Current dosage is 500mg twice daily. Have been stable on this medication for 6 months.',
    status: 'completed',
    createdAt: new Date('2024-01-15T10:30:00'),
    updatedAt: new Date('2024-01-15T16:20:00'),
    zipCode: '10004',
    pharmacy: {
      name: 'Walgreens',
      address: '456 Broadway, New York, NY 10004',
      phone: '(555) 234-0000'
    },
  },
  {
    id: '3',
    patientId: '5',
    patient: mockPatients[4],
    providerId: '3',
    provider: mockProviders[2],
    type: 'prescription-request',
    symptoms: 'Acne treatment',
    description: 'Looking for topical acne treatment. Have been experiencing moderate acne breakouts on face and back for past month.',
    status: 'accepted',
    createdAt: new Date('2024-01-22T14:15:00'),
    updatedAt: new Date('2024-01-22T15:45:00'),
    zipCode: '10005',
    pharmacy: {
      name: 'Rite Aid',
      address: '789 5th Ave, New York, NY 10005',
      phone: '(555) 345-0000'
    },
  },
  
  // Pending Prescription Requests (Multiple new cases)
  {
    id: '4',
    patientId: '6',
    patient: mockPatients[5],
    type: 'prescription-request',
    symptoms: 'Allergic reaction, seasonal allergies',
    description: 'Experiencing severe seasonal allergies - runny nose, sneezing, itchy eyes. Need antihistamine prescription. Previously took Claritin but need stronger medication.',
    status: 'pending',
    createdAt: new Date('2024-01-25T08:30:00'),
    updatedAt: new Date('2024-01-25T08:30:00'),
    zipCode: '10006',
    pharmacy: {
      name: 'CVS Pharmacy',
      address: '321 Park Ave, New York, NY 10006',
      phone: '(555) 456-0000'
    },
  },
  {
    id: '5',
    patientId: '7',
    patient: mockPatients[6],
    type: 'prescription-request',
    symptoms: 'Back pain, muscle strain',
    description: 'Pulled my lower back lifting heavy boxes at work 3 days ago. Pain is getting worse, need muscle relaxant and pain medication.',
    status: 'pending',
    createdAt: new Date('2024-01-25T12:15:00'),
    updatedAt: new Date('2024-01-25T12:15:00'),
    zipCode: '10007',
    pharmacy: {
      name: 'Duane Reade',
      address: '654 7th St, New York, NY 10007',
      phone: '(555) 567-0000'
    },
  },
  {
    id: '6',
    patientId: '8',
    patient: mockPatients[7],
    type: 'prescription-request',
    symptoms: 'UTI symptoms',
    description: 'Experiencing burning sensation when urinating, frequent urination, and pelvic discomfort. These symptoms started 2 days ago and are getting worse.',
    status: 'pending',
    createdAt: new Date('2024-01-25T16:45:00'),
    updatedAt: new Date('2024-01-25T16:45:00'),
    zipCode: '10008',
    pharmacy: {
      name: 'Walgreens',
      address: '987 8th Ave, New York, NY 10008',
      phone: '(555) 678-0000'
    },
  },
  {
    id: '7',
    patientId: '9',
    patient: mockPatients[8],
    type: 'prescription-request',
    symptoms: 'High blood pressure',
    description: 'Need to refill blood pressure medication (Lisinopril 10mg). Have been taking this for 2 years, last refill was 30 days ago. BP has been well controlled.',
    status: 'pending',
    createdAt: new Date('2024-01-25T19:20:00'),
    updatedAt: new Date('2024-01-25T19:20:00'),
    zipCode: '10009',
    pharmacy: {
      name: 'CVS Pharmacy',
      address: '147 9th St, New York, NY 10009',
      phone: '(555) 789-0000'
    },
  },
  {
    id: '8',
    patientId: '10',
    patient: mockPatients[9],
    type: 'prescription-request',
    symptoms: 'Anxiety, panic attacks',
    description: 'Having increased anxiety and occasional panic attacks over past 2 weeks. Work stress has been overwhelming. Need short-term anxiety medication.',
    status: 'pending',
    createdAt: new Date('2024-01-26T09:10:00'),
    updatedAt: new Date('2024-01-26T09:10:00'),
    zipCode: '10010',
    pharmacy: {
      name: 'Rite Aid',
      address: '258 10th Ave, New York, NY 10010',
      phone: '(555) 890-0000'
    },
  },
  {
    id: '9',
    patientId: '11',
    patient: mockPatients[10],
    type: 'prescription-request',
    symptoms: 'Migraine headaches',
    description: 'Suffering from severe migraines 3-4 times per week. Current over-the-counter medications not effective. Need prescription migraine medication.',
    status: 'pending',
    createdAt: new Date('2024-01-26T11:30:00'),
    updatedAt: new Date('2024-01-26T11:30:00'),
    zipCode: '10001',
    pharmacy: {
      name: 'Duane Reade',
      address: '369 1st Ave, New York, NY 10001',
      phone: '(555) 901-0000'
    },
  },
  {
    id: '10',
    patientId: '12',
    patient: mockPatients[11],
    type: 'prescription-request',
    symptoms: 'Insomnia, sleep disturbance',
    description: 'Unable to fall asleep for past 2 weeks. Tried melatonin and sleep hygiene changes with no improvement. Need prescription sleep aid.',
    status: 'pending',
    createdAt: new Date('2024-01-26T14:45:00'),
    updatedAt: new Date('2024-01-26T14:45:00'),
    zipCode: '10002',
    pharmacy: {
      name: 'CVS Pharmacy',
      address: '741 2nd St, New York, NY 10002',
      phone: '(555) 012-0000'
    },
  },
  
  // Lab Test Requests
  {
    id: '11',
    patientId: '2',
    patient: mockPatients[1],
    type: 'lab-test-request',
    symptoms: 'Routine annual checkup',
    description: 'Requesting comprehensive metabolic panel, lipid profile, and CBC for annual physical examination.',
    status: 'pending',
    createdAt: new Date('2024-01-24T16:45:00'),
    updatedAt: new Date('2024-01-24T16:45:00'),
    zipCode: '10002',
  },
  {
    id: '12',
    patientId: '4',
    patient: mockPatients[3],
    providerId: '8',
    provider: mockProviders[7],
    type: 'lab-test-request',
    symptoms: 'Diabetes monitoring',
    description: 'Need A1C test and glucose monitoring for diabetes management. Last test was 3 months ago.',
    status: 'accepted',
    createdAt: new Date('2024-01-23T13:20:00'),
    updatedAt: new Date('2024-01-24T08:15:00'),
    zipCode: '10004',
  },
  
  // General Consultations
  {
    id: '13',
    patientId: '1',
    patient: mockPatients[0],
    providerId: '4',
    provider: mockProviders[3],
    type: 'general-consultation',
    symptoms: 'Anxiety, sleep issues',
    description: 'I have been struggling with anxiety and insomnia for several weeks. It is affecting my work and daily life significantly.',
    status: 'in-progress',
    createdAt: new Date('2024-01-22T13:15:00'),
    updatedAt: new Date('2024-01-23T09:45:00'),
    zipCode: '10001',
  },
  {
    id: '14',
    patientId: '3',
    patient: mockPatients[2],
    type: 'general-consultation',
    symptoms: 'Digestive issues, stomach pain',
    description: 'Experiencing stomach pain and digestive issues after meals for the past week. Pain is sharp and occurs about 30 minutes after eating.',
    status: 'pending',
    createdAt: new Date('2024-01-25T20:30:00'),
    updatedAt: new Date('2024-01-25T20:30:00'),
    zipCode: '10003',
  },
  {
    id: '15',
    patientId: '6',
    patient: mockPatients[5],
    type: 'general-consultation',
    symptoms: 'Fatigue, joint pain',
    description: 'Feeling extremely tired for past 3 weeks, along with joint pain in knees and elbows. Concerned about possible autoimmune condition.',
    status: 'pending',
    createdAt: new Date('2024-01-26T07:45:00'),
    updatedAt: new Date('2024-01-26T07:45:00'),
    zipCode: '10006',
  },
  
  // More prescription requests with different conditions
  {
    id: '16',
    patientId: '2',
    patient: mockPatients[1],
    type: 'prescription-request',
    symptoms: 'Birth control consultation',
    description: 'Looking to start birth control. Need consultation and prescription for oral contraceptives. No previous history of birth control use.',
    status: 'pending',
    createdAt: new Date('2024-01-26T13:15:00'),
    updatedAt: new Date('2024-01-26T13:15:00'),
    zipCode: '10002',
    pharmacy: {
      name: 'Walgreens',
      address: '852 2nd Ave, New York, NY 10002',
      phone: '(555) 234-1111'
    },
  },
  {
    id: '17',
    patientId: '7',
    patient: mockPatients[6],
    type: 'prescription-request',
    symptoms: 'Acid reflux, heartburn',
    description: 'Experiencing severe acid reflux and heartburn daily, especially after meals. Over-the-counter antacids not providing relief.',
    status: 'pending',
    createdAt: new Date('2024-01-26T15:30:00'),
    updatedAt: new Date('2024-01-26T15:30:00'),
    zipCode: '10007',
    pharmacy: {
      name: 'CVS Pharmacy',
      address: '963 7th Ave, New York, NY 10007',
      phone: '(555) 567-1111'
    },
  },
  {
    id: '18',
    patientId: '11',
    patient: mockPatients[10],
    type: 'prescription-request',
    symptoms: 'Depression, mood changes',
    description: 'Experiencing persistent low mood, loss of interest in activities, and fatigue for past month. Think I may need antidepressant medication.',
    status: 'pending',
    createdAt: new Date('2024-01-26T17:00:00'),
    updatedAt: new Date('2024-01-26T17:00:00'),
    zipCode: '10001',
    pharmacy: {
      name: 'Rite Aid',
      address: '741 1st St, New York, NY 10001',
      phone: '(555) 901-1111'
    },
  }
];

export const specialties = [
  'Family Medicine',
  'Internal Medicine',
  'Cardiology',
  'Dermatology',
  'Psychiatry',
  'Pediatrics',
  'Orthopedics',
  'Neurology',
  'Oncology',
  'Endocrinology',
  'Gastroenterology',
  'Pulmonology',
  'Rheumatology',
  'Urology',
  'Ophthalmology',
];

// Pharmacy chains for prescription requests
export const pharmacyChains = [
  'CVS Pharmacy',
  'Walgreens',
  'Rite Aid',
  'Duane Reade',
  'Local Independent Pharmacy',
];

// Simple auth mock - in a real app, this would be handled by a proper auth service
export const mockAuth = {
  currentUser: null as (Provider | Patient) | null,
  
  login: (email: string, password: string, role: 'provider' | 'patient') => {
    if (role === 'provider') {
      const provider = mockProviders.find(p => p.email === email);
      if (provider) {
        mockAuth.currentUser = provider;
        return provider;
      }
    } else {
      const patient = mockPatients.find(p => p.email === email);
      if (patient) {
        mockAuth.currentUser = patient;
        return patient;
      }
    }
    return null;
  },
  
  logout: () => {
    mockAuth.currentUser = null;
  },
  
  isAuthenticated: () => mockAuth.currentUser !== null,
}; 